language: node_js
node_js:
- '8.10'
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.npm"
install:
- npm install
script:
- npm run lint
notifications:
  slack:
    secure: 1br2etbKim8ouoUtG6fpdqJzhoR3LFvz8zxpqC/ko+ig5MOQQASGMAfdT7PJAEK/d0pzj/zXXjib2EvIl0mhPiGHMjYqAZAfzpxRw+QCWpqgYpbTHiwEl/nnNRtojEXG6RpPpcGY05WQt5Tb91Wse+nk9r41G8MxBQiPuI5c34J+vZMD7VIz8T/infXwMV1a1qgQoqgy4IB22GPCbQ1c8/RiI9q1P6Z97PhF3CvGzI2PE48/eI/wHWbLjwhKeKlfRFA9lOFydb1Y4bZM5QXPDKAGhaoLpB8lXmjwimK+AMGu/O3pQEGt/MI3VX9oSwIniVPTZoZXdkJUGPdc1fY2WsGuRuo0lwyKgnGkj4Q870rVrTWkmiJfILAi1/P4SjTQfh/q7KAmcv4A+OQMf3MT9Eu5Jxy4MKxRod6Gb8QB9eNaT/g8WLzQuMfPIqO6HRvZ9F3onU2I5o3bemc5Ih4bX4dA+3Vc+bnhh1fkfSoLWpxWqfp7Mh4O/DcMa8OYxQ5Oqncacb39FH+F4GyApTo0F2HgpSD3gRulHf/2psUVD+EX7z06WYSnKoeYRxkaiomVJwcZ9TA+uRzbzX2LdN1lEwNNm1Q+NB4tA9przQxEWQLGu/fuKxpaklJi6IQyk2TkBw75KEjFrGeJrvMxQq/3LoJwG50LcdKSRGjS9yMoUyo=
